# Generated by Django 3.1.7 on 2021-04-06 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TODO_APP', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todaylist',
            options={'ordering': ['-created_date']},
        ),
        migrations.AlterUniqueTogether(
            name='todaylist',
            unique_together={('title', 'description')},
        ),
    ]
